# Generated by Django 5.2.9 on 2025-12-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodio',
            name='video',
        ),
        migrations.AddField(
            model_name='episodio',
            name='video_url',
            field=models.URLField(blank=True, help_text='Cole aqui o link direto do Google Drive', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='filmes_vistos',
            field=models.ManyToManyField(blank=True, to='filme.filme'),
        ),
    ]
